name: trevorjames
favicon: null
layout_spectrum: 1
typography_spectrum: 0.44354
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1c202b'
    - '#748fbe'
    - '#b8c2cc'
    - '#c69b88'
  brandStrength: 0.7824036958627403
  lightness: 0.7835978679358959
  saturation: 0.24549377406947315
  rhythmicContrast: 0.28125878632999957
purpose: []
