name: trevorjames
favicon: null
layout_spectrum: 0.054344798903912306
typography_spectrum: 0.7720361424144357
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#575036'
    - '#ccb296'
    - '#827857'
    - '#100f0a'
  brandStrength: 0.7824036958627403
  lightness: 0.7835978679358959
  saturation: 0.24549377406947315
  rhythmicContrast: 0.28125878632999957
purpose: []
